---
version: "3.7"

networks:
  monitor:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data:

services:
  grafana:
    image: grafana/grafana-arm64v8-linux:latest 
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - monitor
    labels:
      org.label-schema.group: "monitor"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    environment:
      - PROMETHEUS_DISABLE_CREATED_SERIES=True
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=200h'
    networks:
      - monitor
    labels:
      org.label-schema.group: "monitor"
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    volumes:
      - "./alertmanager:/config"
      - alertmanager-data:/data
    command:
      - '--config.file=/config/alertmanager.yml --log.level=debug'
    ports:
      - "9093:9093"
    networks:
      - monitor
    labels:
      org.label-schema.group: "monitor"
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    networks:
      - monitor
    labels:
      org.label-schema.group: "core"
