---
global:
  scrape_interval: 5s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: 'main'
    static_configs:
      - targets: ['main:8000']