---
groups:
  - name: DemoAlerts
    rules:
      - alert: InstanceDown 
        expr: up{job="main"} < 1 
        for: 1m
        labels:
          severity: low
        annotations:
          summary: 'Alert with low severity.'

      - alert: InstanceDownCritical
        expr: up{job="main"} < 1 
        for: 1m 
        labels:
          severity: high
        annotations:
          summary: 'Alert with high severity.'